### ISSUE TITLE
香港服务器调用openai接口会被停用账号,别问我怎么知道的

### ISSUE THREAD

**Issue by yjj5855** [zuoFeng59556/chatGPT#2]

**Comment by zuoFeng59556** [comment]
封号目前不确定是什么因素导致的，但和香港服务器调用 openai 接口没有一定的关系，此项目在线地址：https://jyf6wk-chat-gpt.site.laf.dev/ 已经被多人连续使用两天了目前没有封号，我用的 key 是个人免费版。
