### ISSUE TITLE
关于我没一会儿openAi api keys就被封了

### ISSUE THREAD

**Issue by sheng3233836** [zuoFeng59556/chatGPT#3]
问下大佬，这个怎么解决，升级plus？laf是香港的 是不是也是不支持的地区哦？还是要找个稳定的机场，或者找个海外的机器架一下服务~~

**Comment by zuoFeng59556** [comment]
> 问下大佬，这个怎么解决，升级plus？laf是香港的 是不是也是不支持的地区哦？还是要找个稳定的机场，或者找个海外的机器架一下服务~~
封号比较玄学，和地区无关，后面 laf 会上东京节点，不知是否会好一些。
