### ISSUE TITLE
输入框好像不能换行，很难受。。

### ISSUE THREAD

**Issue by enguangouyang** [zuoFeng59556/chatGPT#4]

**Comment by zuoFeng59556** [comment]
很快更新

**Comment by enguangouyang** [comment]
感谢
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月15日 17:25
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [zuoFeng59556/chatGPT] 输入框好像不能换行，很难受。。 (Issue #4)
        
      
    
  

很快更新

**Comment by zuoFeng59556** [comment]
忘记回复了，早已更新
