### ISSUE TITLE
是否可以实现输出的效果和官方一样（打字效果）

### ISSUE THREAD

**Issue by mengdahuang** [zuoFeng59556/chatGPT#5]
如题，是否可以实现输出的效果和官方一样（打字效果）？

**Comment by zuoFeng59556** [comment]
> 如题，是否可以实现输出的效果和官方一样（打字效果）？

我来试试

**Comment by mengdahuang** [comment]
@zuoFeng59556  我看这位的效果就是那样
https://github.com/binjie09/chatgpt-web

**Comment by zuoFeng59556** [comment]
功能经群友投票不实用，不补充了
