### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by just2022try** [zuoFeng59556/chatGPT#6]
老哥好，很感谢您，学习到了很多，但是奈何前段知识匮乏，特此像您请教一下。
① 手机端的键盘升起会挡住输入框，请问是否可以设计输入框和键盘一同升起
② 做成官网效果的瀑布流输出
③ Chatgpt4

**Comment by zuoFeng59556** [comment]
> 老哥好，很感谢您，学习到了很多，但是奈何前段知识匮乏，特此像您请教一下。 ① 手机端的键盘升起会挡住输入框，请问是否可以设计输入框和键盘一同升起 ② 做成官网效果的瀑布流输出 ③ Chatgpt4

你好感谢关注，手机键盘会挡住输入是什么手机型号呀，我的手机不会挡住，剩下两个需求可能需要点时间，这两天工作太忙抽不出空
