### ISSUE TITLE
NoSuchKey怎么回事？

### ISSUE THREAD

**Issue by hanlihub** [zuoFeng59556/chatGPT#7]
![1678965863514](https://user-images.githubusercontent.com/54395385/225602772-1064230d-9655-479d-ac61-6915ac53f243.jpg)

**Comment by njuptlzf** [comment]
存储用的是对象存储，要把index.html放在根目录

**Comment by hanlihub** [comment]
域名打开后是这个样子，本地打开没问题

**Comment by zuoFeng59556** [comment]
根据你提供的线索我确实无法得知是什么原因

**Comment by Klotting** [comment]
我也遇到这个问题了 在laf上跑也这样
